<div id="main-fixed">
    <div id="title">
        <div id="title-links">
            <a href="<?php echo $this->baseUrl($this->Param('projekt').'/milestone/add') ; ?>">Nový Milník</a> | 
			<a href="<?php echo $this->baseUrl($this->Param('projekt').'/ticket/add') ; ?>">Nový Ticket</a> | 
			<a href="<?php echo $this->baseUrl($this->Param('projekt').'/checklist/add') ; ?>">Nový Checklist</a>
        </div>
        <h2>Přehled projektu</h2>
    </div>

</div>

<div id="side">
	<div class="block">
	    <h3>Postup práce</h3>
	    <div class="bar center">
	        <div style="width: 15%">
	        </div>
	    </div>
		<div id="progress-info"><strong>1</strong> ze <strong>7</strong> úkolů dokončeno (<strong>15%</strong>)</div>
	</div>
	
	<div class="block">
		<h3>Lidé přiřazení k projektu</h3>
	</div>
</div>
