<div id="main-fixed">
   <div id="title">
      <div id="title-links">

      </div>
      <h2><?php echo $this->Translate('Dashboard'); ?></h2>

   </div>
   <div id="obsah">


            <?php
	    $zdatum = new Zend_Date();
            foreach($this->stream as $date => $item):
	       if($this->acl($date.'|index', 'index')):
            ?>

      <table class="skin stream">
	 <thead>
	    <tr>
	       <th colspan="5"><a href="<?=$date;?>/index/overview"><?=$item['project'];?></a></th>
	    </tr>
	 </thead>
	 <tbody>
            <?php
            foreach($item['data'] as $stream):
	       $datum = $zdatum->set($stream->datetime);
            ?>

            	    <tr class="<?php echo $this->cycle(array('', 'even'))->next()?>">
		       <td class="gravatar"><?=$this->Gravatar($stream->email, 30); ?></td>
		       <td class="content">
			  <div class="title">
			     <div class="stream"><?= $this->streamTyp($stream->typ) ?></div>
			     <span class="title"><a href="<?= $this->baseUrl($project.'/redir/'.$stream->typ.'x'.$stream->link) ?>"><?= $stream->title ?></a></span>
			     <span class="user"><?= $this->streamAkce($stream->akce, $stream) ?></span>
			     <div class="time"><?=$datum->get(Zend_Date::TIME_SHORT);?></div>
			  </div>
		       </td>
		    </tr>

	    <?php endforeach; ?>


	 </tbody>
      </table>

<?php endif; endforeach; ?>



      <br class="clear" />


   </div>
</div>
 
	
		
		
<div id="side">
	<div class="block">
	    <h3>Postup práce</h3>
	    <div class="bar center">
	        <div style="width: 15%">
	        </div>
	    </div>
		<div id="progress-info"><strong>1</strong> ze <strong>7</strong> úkolů dokončeno (<strong>15%</strong>)</div>
	</div>
	
	<div class="block">
		<h3>Lidé přiřazení k projektu</h3>
	</div>
</div>
