<div id="main-fixed">
   <div id="title">
      <div id="title-links">

      </div>
      <h2><?php echo $this->Translate('Dashboard'); ?></h2>

   </div>
   <div id="obsah">


            <?php
	    $zdatum = new Zend_Date();
            foreach($this->stream as $date => $item):
	       if($this->acl($date.'|index', 'index')):
            ?>

      <table class="skin stream">
	 <thead>
	    <tr>
	       <th colspan="5"><a href="<?=$date;?>/index/overview"><?=$item['project'];?></a></th>
	    </tr>
	 </thead>
	 <tbody>
            <?php
            foreach($item['data'] as $stream):
	       $datum = $zdatum->set($stream->datetime);
            ?>

            	    <tr class="<?php echo $this->cycle(array('', 'even'))->next()?>">
            	       <td class="typ"><div class="stream t-<?=$stream->typ;?>"><?= $this->streamTyp($stream->typ) ?></div></td>
            	       <td class="title"><a href="<?= $this->baseUrl('/redir/'.$stream->typ.'x'.$stream->link) ?>"><?= $stream->title ?></a></td>
            	       <td class="right action"><?= $this->streamAkce($stream->akce) ?>: </td>
            	       <td class="user"><a href="/people/detail/<?= $stream->iduser ?>"><?= $stream->surname . ' ' . $stream->name; ?></a></td>
		       <td class="time"><?=$datum->get(Zend_Date::TIME_SHORT);?></td>
            	    </tr>

	    <?php endforeach; ?>


	 </tbody>
      </table>

<?php endif; endforeach; ?>



      <br class="clear" />


   </div>
</div>
 
	
		
		
<div id="side">
	<div class="block">
	    <h3>Postup práce</h3>
	    <div class="bar center">
	        <div style="width: 15%">
	        </div>
	    </div>
		<div id="progress-info"><strong>1</strong> ze <strong>7</strong> úkolů dokončeno (<strong>15%</strong>)</div>
	</div>
	
	<div class="block">
		<h3>Lidé přiřazení k projektu</h3>
	</div>
</div>
