<?php
$this->headTitle($this->Translate('Overview'));

$project = $this->Param('projekt');
?>



<div id="main-fixed">
   <div id="title">
      <div id="title-links">
	 <?php if($this->acl($project . '|milestone', 'new')): ?>
         <?=$this->ActionLink('/milestone/new', 'Create New Milestone', true); ?>
         <?php endif; ?>
      </div>
      <h2><?php echo $this->Translate('Overview'); ?></h2>				
   </div>
   <div id="obsah">
      <?=$this->flashMessages(); ?>
      
      <?php
      if($this->info->img == null)
         $img = 'design/placeholder.gif';
      else
         $img = 'files/' . $this->info->idaccount . '/' . $this->info->idproject . '/' . $this->info->img;
      ?>



      <div id="overview">
	 <div class="main">
	    <img src="/public/<?=$img;?>" class="logo" />
	    <h3><?=$this->info->name;?></h3>
	    <p><?=$this->info->description;?></p>
	    <dl>
	      <dt><?=$this->Translate('Leader');?>:</dt>
	       <dd><a href="/people/detail/<?=$this->info->iduser;?>"><?=$this->info->user;?></a></dd>
	      <dt><?=$this->Translate('Client');?>:</dt>
	       <dd><a href="/<?=$this->info->idcompany;?>"><?=$this->info->company;?></a></dd>
	      <dt><?=$this->Translate('Status');?>:</dt>
	       <dd><?=$this->Translate($this->info->status);?></dd>
	      <dt><?=$this->Translate('Progress');?>:</dt>
	       <dd><strong>1</strong> ze <strong>7</strong> úkolů dokončeno (<strong>15%</strong>)</dd>
	    </dl>
	 </div>
	 <div class="graph">
	    <!--<img src="/public/design/graph.png" />-->
	    <img src="/index/img?data=15" title="Progress" />
	 </div>
      </div>




      <div id="tabs">
	<ul class="tabs">
		<li><a href="#" rel="/ajax/stream/<?=$project?>"><?=$this->Translate('Latest Activity');?></a></li>
		<li><a href="#" rel="/ajax/late/<?=$project?>"><?=$this->Translate('Late');?></a></li>
		<li><a href="#" rel="/ajax/upcoming/<?=$project?>"><?=$this->Translate('Upcoming');?></a></li>
	</ul>
      </div>








      <br class="clear" />


   </div>
</div>

<div id="side">
	 <h3><?=$this->Translate('People on project')?></h3>
	<div class="block">
	   <?php foreach($this->users as $company): ?>
		<h4><?=$company['company']?></h4>
		<?php foreach($company['user'] as $user): ?>
		<div class="user">
		   <?=$this->Gravatar($user->email, 30); ?>
		   <a href="<?=$this->baseUrl('people/detail/'.$user->iduser)?>"><?=$user->name?></a>
		   <div class="status">Now online</div>
		</div>
		<?php endforeach; ?>
	   <?php endforeach; ?>
	</div>

	<div class="block">
		<h3><?=$this->Translate('Subscriptions')?></h3>
	</div>
</div>