<?php
$project = $this->Param('projekt');

?>



<div id="main-fixed">
   <div id="title">
      <div id="title-links">
	 <?php if($this->acl($project . '|milestone', 'new')): ?>
         <?=$this->ActionLink('/milestone/new', 'Create New Milestone', true); ?>
         <?php endif; ?>
      </div>
      <h2><?php echo $this->Translate('Overview'); ?></h2>				
   </div>
   <div id="obsah">
      <?=$this->flashMessages(); ?>

      <div class="overview">
	 <img src="/public/design/placeholder.gif" />
	 <a href="#">Název Projektu</a>
	 <p>Nějaký popis tohoto projektu</p>
      </div>



            <?php
	    $zdatum = new Zend_Date();
            foreach($this->stream as $date => $item):
            ?>

      <table class="skin stream">
	 <thead>
	    <tr>
	       <th colspan="5"><?=$date;?></th>
	    </tr>
	 </thead>
	 <tbody>
            <?php
	    $i=0;
            foreach($item as $stream):
	       $datum = $zdatum->set($stream->datetime);
            ?>

            	    <tr class="<?php echo $this->cycle(array('', 'even'))->next()?>">
		       <td class="gravatar"><?=$this->Gravatar($stream->email, 30); ?></td>
		       <td class="content">
			  <div class="title">
			     <div class="stream"><?= $this->streamTyp($stream->typ) ?></div>
			     <span class="title"><a href="<?= $this->baseUrl($project.'/redir/'.$stream->typ.'x'.$stream->link) ?>"><?= $stream->title ?></a></span>
			     <span class="user"><?= $this->streamAkce($stream->akce, $stream) ?></span>
			     <div class="time"><?=$datum->get(Zend_Date::TIME_SHORT);?></div>
			  </div>
			     
			  
		       <?php if($i == 3){
			 echo '<ul class="subinfo"><li>Ticket reassigned from Daniel Marchlík to Mikoláš Lebeda</li> <li>Další kecy</li></ul>';
		       }
		       ?>
			  
		       </td>
		       
		    </tr>


	    <?php $i++; endforeach; ?>


	 </tbody>
      </table>

<?php endforeach; ?>



      <br class="clear" />


   </div>
</div>

<div id="side">
	 <h3><?=$this->Translate('Progress')?></h3>
	<div class="block">	    
	    <div class="bar center">
	        <div style="width: 15%">
	        </div>
	    </div>
		<div id="progress-info"><strong>1</strong> ze <strong>7</strong> úkolů dokončeno (<strong>15%</strong>)</div>
	</div>

	 <h3><?=$this->Translate('People on project')?></h3>
	<div class="block">
	   <?php foreach($this->users as $company): ?>
		<h4><?=$company['company']?></h4>
		<?php foreach($company['user'] as $user): ?>
		<div class="user">
		   <?=$this->Gravatar($user->email, 30); ?>
		   <a href="<?=$this->baseUrl('people/detail/'.$user->iduser)?>"><?=$user->name?></a>
		   <div>Now online</div>
		</div>
		<?php endforeach; ?>
	   <?php endforeach; ?>
	</div>

	<div class="block">
		<h3><?=$this->Translate('Subscriptions')?></h3>
	</div>
</div>