<div id="main">
   <div id="title">
      <div id="title-links">
         <?php if($this->acl($this->Param('projekt') . '|milestone', 'new')): ?>
                                                         <?=$this->ActionLink('/milestone/new', 'Create New Milestone', true); ?>
         <?php endif; ?>
               </div>
               <h2><?php echo $this->Translate('Milestones'); ?></h2>
            </div>
            <div id="obsah">
      <?php echo $this->flashMessages(); ?>

<?php
   //echo $this->partialLoop('milestone/partials/table.phtml', $this->data);
   
   foreach($this->data as $name => $data):
      if(!is_null($data)):
	 $this->cycle()->rewind();
   ?>
	       
	       
	       


	       
<table class="milestone <?=$name?>">
      	 <thead>
      	    <tr>
      	       <th colspan="2" class="<?=$name?>"><?php echo $this->Translate($name); ?> (<?php echo count($data); ?>)</th>
      	    </tr>
      	 </thead>
      	 <tbody>
      	    <?php
	    $now = new Zend_Date(null, 'MM.dd.yyyy');
	    foreach($data as $milestone):
               $due = new Zend_Date($milestone->datetime);

               $over = $now->compare($due); //0 = equal, 1 = later, -1 = earlier

	       if($over == 1){
		  $late = 'late';
	       }elseif($over == 0){
		  $late = 'today';
	       }else{
		  $late = '';
	       }

               $date = $due->get(Zend_Date::DATE_FULL, 'cs_CZ');

               $sub = $due->sub($now);

               $num = ceil($sub->get(Zend_Date::TIMESTAMP) / 60 / 60 / 24);
            ?>
      	    <tr class="<?php echo $this->cycle(array('', 'even'))->next()?> <?=$late;?>">
      	       <td class="name">
		  <div class="date <?=$late;?>">
		    <?php

		       if(abs($num) == 0){
			  echo $this->Translate('Today');
		       }else{
			   echo $this->Translate(array('%s day', '%s days', $num), abs($num));
			   echo ' ';
			   echo $num > 0 ? $this->Translate('away') : $this->Translate('ago');
		       }

		     echo ' (' . $date . ')';
		    ?>
		  </div>
      		  <a href="milestone/detail/<?php echo $milestone->idmilestone; ?>" class="title"><?php echo $milestone->name; ?></a>
      		  <p><strong><?php echo $this->Translate('Assigned to'); ?></strong>


		     <?php foreach($milestone->users as $user): ?>
			<a href="/people/detail/<?= $user->iduser ?>"><?= $user->name . ' ' . $user->surname; ?></a>,
		     <?php endforeach; ?>


      		  </p>
      	       </td>
      	       <td class="status">status</td>
      	    </tr>
      	    <?php endforeach; ?>
      	 </tbody>
            </table>
	       
	       
	       
	       
	       
	       
	       
	       
	       
	       
	       
	       
	       
      
<?php endif; endforeach;?>

      <br class="clear" />


   </div>
</div>