<div id="main-fixed">
    <div id="title">
         <div id="title-links">
         <?php if($this->acl($this->Param('projekt').'|milestone', 'new')): ?>
            <a href="<?php echo $this->baseUrl($this->Param('projekt').'/milestone/new') ; ?>"><?php echo $this->Translate('Create new milestone'); ?></a>
         <?php endif; ?>  
        </div>    
        <h2><?php echo $this->Translate('Milestones'); ?></h2>
    </div>
	<div id="obsah">
		<?php echo $this->flashMessages(); ?>
				
				
		
				
				
				
					
		<br class="clear" />

		
	</div>
</div>