<?php // TODO nastaveni podle locale ?>
<script type="text/javascript">
	$(function() {
		$('#datepicker').datepicker('option', $.extend($.datepicker.regional['cs']));		
	});	
</script>

<div id="main-fixed">
    <div id="title">
        <h2><?php echo $this->Translate('New Milestone'); ?></h2>
    </div>
	<div id="obsah">	
		<?php echo $this->flashMessages(); ?>
		<?php echo $this->form; ?>
	
		
		<br class="clear" />
	</div>
</div>

<div id="side">
	<div class="block">
		<h3>What are statuses?</h3>
		<p>Milestones can be assigned statuses which denote it's current position within your project. Active milestones imply you are currently working toward it. Completed implies it has been finished and all work required is finished, cancelled means you no longer are working on this milestone and it has outstanding tickets which no longer need to be completed.</p>
	</div>
</div>