<div id="main-fixed">
   <div id="title">
      <div id="title-links">
         <?php
         if($this->acl('people', 'delete')){
            echo $this->ActionLink('/people/delete/' . $this->user->iduser, 'Remove this Person', false, true);
         }
         ?>
      </div>
      <h2><?=$this->Translate('Edit %s', $this->user->name . ' ' . $this->user->surname); ?></h2>
   </div>
   <div id="obsah">
      <?php
      echo $this->flashMessages();
      echo $this->form;
      ?>

      <br class="clear" />
   </div>
</div>

<div id="side">
   <div class="block">
      <h3>Welcome Email</h3>
      <p>text</p>
   </div>

   <div class="block">
      <h3>Project assignment</h3>
      <p>text</p>
   </div>
</div>