<div id="main">
    <div id="title">
         <div id="title-links">
            <?php if($this->acl('people', 'new')): ?>
            <?=$this->ActionLink('/people/new', 'Create new User');?>
            <?php endif; ?>
        </div>
        <h2><?php echo $this->Translate('Users'); ?></h2>
    </div>

	<div id="obsah">
		<?php echo $this->flashMessages(); ?>
		
		<?php foreach($this->userList as $company => $users): ?>

		<table class="skin people-table">
			<thead>
				<tr>
					<th colspan="4"><?php echo $company; ?><a href="<?php echo $this->baseUrl('/company/edit/'.$users[0]['idcompany']); ?>" class="actionlink"> <?php echo $this->translate('Edit Company') ?></a></th>
				</tr>
			</thead>

			<?php
			$i = 0;
			foreach($users as $user): ?>
			<tr class="hidden-action-container <?php echo ($i % 2 == 0 ? '' : 'even') ?>">
				<td width="50px"><?=$this->Gravatar($user['email'], '40');?></td>
				<td>
					<a href="<?php echo $this->baseUrl('/people/detail/'.$user['iduser']); ?>" class="title"><?php echo $user['user']; ?></a> (<?=$user['username'];?>)
					<p><?php echo $user['email']; ?></p>
				</td>

				<td colspan="1">
				<?php if($this->acl('people', 'edit')): ?>
				<div class="hidden-action">
				<a href="<?php echo $this->baseUrl('/people/edit/'.$user['iduser']); ?>" class="actionlink"> <?php echo $this->translate('Edit') ?></a>
				<a href="<?php echo $this->baseUrl('/people/delete/'.$user['iduser']); ?>" class="actionlink delete"> <?php echo $this->translate('Remove') ?></a>
				</div>
				<?php endif; ?>
				</td>

				<td class="right"  colspan="1"><span class="status <?=$user['status'] == 1 ? 'active' : 'noactive';?>"><?=$user['status'] == 1 ? $this->translate('Account is active') : 'Uživatel svůj účet ještě neaktivoval';?></span></td>
				

			</tr>
			<?php
			$i++;
			endforeach; ?>

		</table>
		<?php endforeach; ?>	





		<br class="clear" />
	</div>
</div>