<div id="main-fixed">
    <div id="title">
        <h2><?php echo $this->Translate('New Team member'); ?></h2>
    </div>
	<div id="obsah">
		<?php echo $this->flashMessages(); ?>
		<?php echo $this->form; ?>
		
		<br class="clear" />
	</div>
</div>

<div id="side">
	<div class="block">
	    <h3>Welcome Email</h3>
	    <p>text</p>
	</div>

	<div class="block">
		<h3>Project assignment</h3>
		<p>text</p>
	</div>
</div>