<div id="main">
    <div id="title">
        <h2><?php echo $this->Translate('New Team member'); ?></h2>
    </div>
	<div id="obsah">
	<?php echo $this->flashMessages(); ?>
<form method="post">

<select id="userSelect" multiple="multiple" name="user[]" size="15">
	<?php foreach($this->users as $company => $users): ?>
		<optgroup label="<?php echo $company ?>" id="opt-<?php echo $company;?>">
			<?php foreach($users as $user):?>
				<option value="<?php echo $user['iduser']; ?>"><?php echo $user['user']; ?></option>
			<?php endforeach; ?>	
		</optgroup>
	<?php endforeach; ?>
</select>

		<table class="acl">
			<thead>
				<tr>
					<th>Sekce</th>
					<th colspan="4">Oprávnění</th>
				</tr>
			</thead>
			<tbody>
				<?php $i = 0; 
				foreach($this->resources as $name => $resource):
					if($name == 'index') continue;
				?>
				<tr <?php echo ($i % 2 == 0 ? '' : 'class="even"') ?>>
					<td><?php echo $this->translate($resource)?></td>
					<td class="noaccess"><?php echo $this->formRadio('acl['.$name.']', null, array('class' => 'input-radio acl'), array('0' => $this->translate('No access'))); ?></td>
					<td class="read"><?php echo $this->formRadio('acl['.$name.']', null, array('class' => 'input-radio acl'), array('1' => $this->translate('Read only'))); ?></td>
					<td class="create"><?php echo $this->formRadio('acl['.$name.']', null, array('class' => 'input-radio acl'), array('3' => $this->translate('Can create'))); ?></td>
					<td class="manage"><?php echo $this->formRadio('acl['.$name.']', 7, array('class' => 'input-radio acl'), array('7' => $this->translate('Can manage'))); ?></td>
				</tr>				
				<?php $i++; endforeach; ?>
			</tbody>
		</table>
		<br class="clear" />
		<hr />
		
		<div class="submit-block">
			<?php echo $this->formSubmit('submit', $this->translate('Save'), array('class' => 'input-submit')); ?> <?php echo $this->translate('or')?> 
			<a href="<?php echo $this->baseUrl($this->param('projekt').'/people/overview')?>" class="cancel"><?php echo $this->translate('Cancel')?></a>
		</div>
		
		</form>

	</div>
</div>