<div id="main-fixed">
    <div id="title">
         <div id="title-links">
         <?php if($this->acl('people', 'new')): ?>
            <a href="<?php echo $this->baseUrl($this->Param('projekt').'/people/new') ; ?>"><?php echo $this->Translate('Add people to project'); ?></a>
         <?php endif; ?>  
        </div>    
        <h2><?php echo $this->Translate('Project Team'); ?></h2>
    </div>
	<div id="obsah">
		<?php echo $this->flashMessages(); ?>
		<hr class="clear" />
		<?php foreach($this->userList as $company => $users): ?>
		
		<table class="people-overview">
			<thead>
				<tr>
					<th colspan="4"><?php echo $company; ?></th>
				</tr>
			</thead>
			
			<?php 
			$i = 0;
			foreach($users as $user): ?>
			<tr <?php echo ($i % 2 == 0 ? '' : 'class="even"') ?>>
				<td><a href="<?php echo $this->baseUrl('/people/detail/'.$user['iduser']); ?>"><?php echo $user['user']; ?></a></td>
				<td><?php echo $user['email']; ?></td>
				<td colspan="1" class="small-cell">
				<?php if($this->acl('people', 'edit')): ?>
				<a href="<?php echo $this->baseUrl($this->Param('projekt').'/people/edit/'.$user['idacl']); ?>" class="modal"><img src="<?php echo $this->baseUrl('/public/design/ico-key.png') ?>" title="<?php echo $this->translate('Change Permissions') ?>" /></a>
				<a href="<?php echo $this->baseUrl($this->Param('projekt').'/people/delete/'.$user['idacl']); ?>"><img src="<?php echo $this->baseUrl('/public/design/ico-cross.png') ?>" title="<?php echo $this->translate('Remove from Project') ?>" /></a>
				<?php endif; ?>
				</td>
			</tr>
			<?php 
			$i++;
			endforeach; ?>
			
		</table>
		<?php endforeach; ?>	

		
		
		<br class="clear" />
		
	</div>
</div>