<div id="main-fixed">
    <div id="title">
         <div id="title-links">
            <?php if($this->acl('project', 'new')): ?>
            <?=$this->ActionLink('/project/new', 'Create New Project');?>
            <?php endif; ?>
        </div>    
        <h2><?php echo $this->Translate('Projects'); ?></h2>
    </div>
	<div id="obsah">
		
		<?php 
		foreach($this->project as $row):
		if($this->acl($row->idproject.'|index', 'index')):
		?>	
		<div class="project-table">
			<div class="content">
				<?php 
					if($row->img == null)
						$img = 'design/placeholder.gif';
					else 
						$img = 'files/1/'.$row->idproject.'/'.$row->img;	
				?>				
					<dl>
						<?php if(!is_null($row->iduser)): ?>
						<dt><?php echo $this->Translate('Leader'); ?>:</dt>
					  	<dd><a href="<?php echo $this->baseUrl('/people/detail/'.$row->iduser) ; ?>"><?php echo $row->user;?></a></dd>
					  	<?php 
					  		endif;
					  		if(!is_null($row->idcompany)): 
					  	?>
					  	<dt><?php echo $this->Translate('Client'); ?>:</dt>
					  	<dd><a href="<?php echo $this->baseUrl('/company/detail/'.$row->idcompany) ; ?>"><?php echo $row->company; ?></a></dd>
					  	<?php endif;?>
					</dl>
					<img src="../public/<?php echo $img; ?>" />
				
				<div class="right">
					<a href="<?php echo $this->baseUrl($row->idproject.'/index/overview') ; ?>" class="title"><?php echo $row->name; ?></a>
					<p><?php echo nl2br($row->description, true); ?></p>					
				</div>
				
				<div class="bar-container">
					<div class="bar-project">
		        		<?php echo $this->Bar(rand(0, 100)); ?>
		    		</div>
		    	</div>	
				
				<br class="clear" />
			</div>
		</div>
		<?php 
		endif;
		endforeach;		
		?>
		
		
		<br class="clear" />
	</div>
</div>