<div id="main">
    <div id="title">
        <h2><?php echo $this->Translate('Projekty'); ?></h2>
    </div>
	<div id="obsah">
		
		<?php 
		foreach($this->project as $row):
		?>	
		<div class="project-table">
			<div class="top"></div>
			<div class="content">
				<?php 
					if($row->img == null)
						$row->img = 'design/placeholder.gif';
				?>
				<img src="../public/<?php echo $row->img; ?>" />
				<div class="right">
					<a href="<?php echo $this->baseUrl($row->idproject.'/index/overview') ; ?>" class="title"><?php echo $row->name; ?></a>
					<p><?php echo $row->description; ?></p>
					<dl>
						<dt>Vedoucí:</dt>
					  	<dd><a href="<?php echo $this->baseUrl('/people/detail/'.$row->iduser) ; ?>"><?php echo $row->userName .' '. $row->userSurname; ?></a></dd>
					  	<dt>Klient:</dt>
					  	<dd><a href="<?php echo $this->baseUrl('/company/detail/'.$row->idcompany) ; ?>"><?php echo $row->companyName; ?></a></dd>
					  	<dt>Začátek:</dt>
					  	<dd><?php echo $this->DateTime($row->start); ?></dd>
					</dl>
				</div>
				<br class="clear" />
			</div>
			<div class="bottom"></div>
		</div>
		<?php 
		endforeach;		
		?>
		
		
		<br class="clear" />
	</div>
</div>