<div id="main">
    <div id="title">
        <h2><?php echo $this->Translate('Projekty'); ?></h2>
    </div>
	<div id="obsah">
				
		<div class="project-table">
			<div class="top"></div>
			<div class="content">
				<img src="../public/design/placeholder.gif" />
				<div class="right">
					<a href="<?php echo $this->baseUrl('1/index/overview') ; ?>" class="title">Název Projektu</a>
					<p>Popis projektu bla bla bla bla bla bla bla bla lbga</p>
					<dl>
						<dt>Vedoucí:</dt>
					  	<dd><a href="#">Daniel Marchlík</a></dd>
					  	<dt>Klient:</dt>
					  	<dd><a href="#">Vlastní společnost</a></dd>
					  	<dt>Začátek:</dt>
					  	<dd>18. srpen 2009</dd>
					</dl>
				</div>
				<br class="clear" />
			</div>
			<div class="bottom"></div>
		</div>		
		
		<div class="project-table">
			<div class="top"></div>
			<div class="content">
				<img src="../public/design/placeholder.gif" />
				<div class="right">
					<a href="<?php echo $this->baseUrl('1/index/overview') ; ?>" class="title">Název Projektu</a>
					<p>Popis projektu bla bla bla bla bla bla bla bla lbga</p>
					<dl>
						<dt>Vedoucí:</dt>
					  	<dd><a href="#">Daniel Marchlík</a></dd>
					  	<dt>Klient:</dt>
					  	<dd><a href="#">Vlastní společnost</a></dd>
					  	<dt>Začátek:</dt>
					  	<dd>18. srpen 2009</dd>
					</dl>
				</div>
				<br class="clear" />
			</div>
			<div class="bottom"></div>
		</div>
		
		<div class="project-table">
			<div class="top"></div>
			<div class="content">
				<img src="../public/design/placeholder.gif" />
				<div class="right">
					<a href="<?php echo $this->baseUrl('1/index/overview') ; ?>" class="title">Název Projektu</a>
					<p>Popis projektu bla bla bla bla bla bla bla bla lbga</p>
					<dl>
						<dt>Vedoucí:</dt>
					  	<dd><a href="#">Daniel Marchlík</a></dd>
					  	<dt>Klient:</dt>
					  	<dd><a href="#">Vlastní společnost</a></dd>
					  	<dt>Začátek:</dt>
					  	<dd>18. srpen 2009</dd>
					</dl>
				</div>
				<br class="clear" />
			</div>
			<div class="bottom"></div>
		</div>
		
		<div class="project-table">
			<div class="top"></div>
			<div class="content">
				<img src="../public/design/placeholder.gif" />
				<div class="right">
					<a href="<?php echo $this->baseUrl('1/index/overview') ; ?>" class="title">Název Projektu</a>
					<p>Popis projektu bla bla bla bla bla bla bla bla lbga</p>
					<dl>
						<dt>Vedoucí:</dt>
					  	<dd><a href="#">Daniel Marchlík</a></dd>
					  	<dt>Klient:</dt>
					  	<dd><a href="#">Vlastní společnost</a></dd>
					  	<dt>Začátek:</dt>
					  	<dd>18. srpen 2009</dd>
					</dl>
				</div>
				<br class="clear" />
			</div>
			<div class="bottom"></div>
		</div>
		
		<br class="clear" />
	</div>
</div>