<script type="text/javascript">// <![CDATA[
<?php echo "
$(document).ready(function() {
	$('#img').uploadify({
	'uploader'  : '".$this->baseUrl('public/swf/uploadify.swf')."',
	'script'    : 'http://unodor.mybase/project/upload/?__tkn=".Zend_Session::getId()."',
	'cancelImg' : '".$this->baseUrl('public/design/cancel.png')."',
	'auto'      : true,
	'buttonText': '".$this->translate('BROWSE')."',
	'fileDesc'	: '".$this->translate('Image Files')."',
	'fileExt'	: '*.jpg;*.jpeg;*.gif;*.png',
	'folder'    : '".$this->baseUrl('public/files/temp')."',
	onError: function (evt, queueID, fileObj, errorObj) {
			alert(errorObj.info);
			$('.input-submit').removeAttr('disabled');
		},
	onComplete: function (event, queueID, fileObj, response, data) {
	
			/*console.log('event = '+event);
			console.log('queueID = '+queueID);
			console.log('fileObj.name = '+fileObj.name);
			console.log('fileObj.filePath = '+fileObj.filePath);
			console.log('fileObj.size = '+fileObj.size);
			console.log('fileObj.creationDate = '+fileObj.creationDate);
			console.log('fileObj.modificationDate = '+fileObj.modificationDate);
			console.log('fileObj.type = '+fileObj.type);
			console.log('response = '+response);
			console.log('data.fileCount = '+data.fileCount);
			console.log('data.speed = '+data.speed);*/
			
			$('.input-submit').removeAttr('disabled');
			$('#imgUploader').after('<br /><img src=\"/public/files/tmp/'+response+'\" />');
			$('#imgUploader').hide();
			$('#img').after('<input type=\"hidden\" name=\"img\" value=\"'+response+'\" />');
			//alert(response);
		},
	onOpen: function(event, queueID, fileObj){
		$('.input-submit').attr({disabled: 'disabled'});		
	},
	
	onCancel: function(event, queueID, fileObj, data){
	},
	
	onProgress: function(event, queueID, fileObj, data){
		/*console.log('data.percentage = '+data.percentage);
		console.log('data.bytesLoaded = '+data.bytesLoaded);
		console.log('data.speed  = '+data.speed);*/
	}
	
	});
});"; ?>
// ]]></script>

<div id="main">
    <div id="title">
        <h2><?php echo $this->Translate('New Project'); ?></h2>
    </div>
	<div id="obsah">
		<?php echo $this->flashMessages(); ?>
		<?php echo $this->form; ?>
				
		<br class="clear" />
	</div>
</div>