<?php
$this->headLink()
    ->appendStylesheet($this->baseUrl('/public/css/reset.css'), 'screen,projection')
    ->appendStylesheet($this->baseUrl('/public/css/login.css'), 'screen,projection');

echo $this->doctype(); ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<?php
	echo $this->headMeta();
	echo $this->headTitle();
	echo $this->headLink();
	echo $this->headScript();
	?>
</head>
<body>	


<div id="wrapper">
	<div id="login-top"></div>
	
	<div id="loginbox">	  
	<h1>Unodor</h1>
	<?php echo $this->flashMessages(); ?>
	<?php echo $this->form ?>
	
	
	
	</div>	
	<div id="login-bottom"></div>
</div>




<!--
<div id="wrapper">
	<div id="login-top"></div>
	
	<div id="loginbox">	  
	<h1>Unodor</h1>
<form enctype="application/x-www-form-urlencoded" method="post" action="">
 
<dl>
	<dt><label for="username" class="req">Username:</label></dt>
	<dd><input type="text" name="username" id="username" value="" helper="formText" class="input-text" /></dd>
	
	<dt><label for="password" class="req">Heslo:</label></dt>
	<dd><input type="password" name="password" id="password" value="" helper="formPassword" class="input-text" /></dd>
	
	<dt><input type="checkbox" name="remember" id="remember" value="1" helper="formCheckbox" class="input-checkbox" /></dt>
	<dd><label for="remember"> Zapamatovat</label></dd>
	
	<dt><input type="submit" name="save" id="save" value="Přihlásit" helper="formSubmit" class="input-submit" /></dt>
	<dd></dd>
</dl>

</form>	
	
	
	</div>	
	<div id="login-bottom"></div>
</div>
-->

</body>
</html>