<?php $project = $this->Param('projekt'); ?>

<div id="main-fixed">
    <div id="title">
         <div id="title-links">
         <?php if($this->acl($project.'|team', 'new')): ?>
				<?=$this->ActionLink('/team/new', 'Add people to project', true);?>
         <?php endif; ?>  
        </div>    
        <h2><?php echo $this->Translate('Project Team'); ?></h2>
    </div>
	<div id="obsah">
		<?php echo $this->flashMessages(); ?>

		<?php foreach($this->userList as $company => $users): ?>
		
		<table class="skin">
			<thead>
				<tr>
					<th colspan="4"><?php echo $company; ?></th>
				</tr>
			</thead>
			
			<?php 
			foreach($users as $user): ?>
			<tr class="hidden-action-container <?php echo $this->cycle(array('', 'even'))->next()?>">
				<td><a href="<?php echo $this->baseUrl('/people/detail/'.$user['iduser']); ?>"><?php echo $user['user']; ?></a></td>
				<td><?php echo $user['email']; ?></td>
				<td colspan="1" width="245px">
				<?php if($this->acl($project.'|team', 'edit')): ?>
					<div class="hidden-action">
				<?php if($this->isEditable(array($user, $this->leader), 'edit')): ?><a href="<?php echo $this->baseUrl($project.'/team/edit/'.$user['idacl']); ?>" class="modal actionlink"><?= $this->translate('Change Permissions'); ?></a><?php endif; ?>
				<?php if($this->isEditable(array($user, $this->leader), 'delete')): ?><a href="<?php echo $this->baseUrl($project.'/team/delete/'.$user['idacl']); ?>"  class="actionlink delete"><?= $this->translate('Remove from Project'); ?></a><?php endif; ?>
					</div>
				<?php endif; ?>
				</td>
			</tr>
			<?php endforeach; ?>
			
		</table>
		<?php endforeach; ?>	

		
		
		<br class="clear" />
		
	</div>
</div>