<?php
$this->headLink()
    ->appendStylesheet($this->baseUrl('/public/css/layout.css'), 'screen,projection');
    
$this->headScript()
	//->appendFile($this->baseUrl('/public/js/jquery.js'))
	//->appendFile($this->baseUrl('/public/js/jquery-ui.js'))
	->appendFile('http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js')
	->appendFile('http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/jquery-ui.min.js')
	->appendFile('http://jquery-ui.googlecode.com/svn/tags/latest/ui/minified/i18n/jquery-ui-i18n.min.js')
	->appendFile($this->baseUrl('/public/js/jquery.multiselect.js'))
	->appendFile($this->baseUrl('/public/js/jquery.uploadify.js'))
	->appendFile($this->baseUrl('/public/js/swfobject.js'))
	->appendFile($this->baseUrl('/public/js/mybase.modal.js'))
	->appendFile($this->baseUrl('/public/js/mybase.tooltip.js'))
	->appendFile($this->baseUrl('/public/js/mybase.tabs.js'))
	->appendFile($this->baseUrl('/public/js/mybase.js'));    

echo $this->doctype(); ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<?php
	echo $this->headMeta();
	echo $this->headTitle();
	echo $this->headLink();
	echo $this->headScript();
	?>
	
</head>
<body>	

<div id="header">
	<div class="wrap940">
		<?php $session = new Zend_Session_Namespace('Unodor_Account'); ?>
		<h1>
		   <?php
		      if($this->param('projekt') > 0){
			 echo $this->projectH1->name;
			 echo '<span>  ('.$session->name.') </span>';
		      }else{
			echo $session->name;
		      }
		   ?>
		</h1>
		<div id="userinfo">
			<?php $session = new Zend_Session_Namespace('Zend_Auth'); ?>
			<?php echo $this->gravatar($session->storage->email); ?>
			<a href="<?php echo $this->baseUrl('people/edit/'.$session->storage->iduser) ; ?>" class="user"><?php echo $session->storage->name .' '. $session->storage->surname; ?></a>
			<a href="<?php echo $this->baseUrl('auth/settings') ; ?>" class="link">Settings</a>
			<a href="<?php echo $this->baseUrl('auth/logout') ; ?>" class="link">Logout</a>
			<p>Last login: 13.01.2010 11:39</p>
		</div>
	</div>
</div>

<div id="menu">
	<div id="mainmenu">
		<div class="wrap940">
			<?php 
			$acl = Zend_Registry::get('acl');
			$this->navigation()->setAcl($acl)->setRole($session->storage->email);
			echo $this->navigation()->menu()->setMaxDepth(0); ?>
		</div>
	</div>	
	
<?php if($this->param('projekt')): ?>
	<div id="submenu">
		<div class="wrap940">
			<?php 
				if($this->param('projekt') > 0){
					$options = array(    
						'ulClass'		   => 'subnavigation',    
						'indent'           => 4,    
						'minDepth'         => null,    
						'maxDepth'         => 1,    
						'onlyActiveBranch' => true,    
						'renderParents'    => false
					);
					//echo $this->navigation()->menu()->renderSubMenu(null, 'subnavigation', 4);
					echo $this->navigation()->menu()->renderMenu(null, $options);
				}
			?>
		</div>
	</div>

<?php endif; ?>
</div>
<div class="wrap940 clear">

	<?php echo $this->layout()->content ?>
	
	<br class="clear" />
</div>	

</body>
</html>