<?php
$this->headLink()
    ->appendStylesheet($this->baseUrl('/public/css/reset.css'), 'screen,projection')
    ->appendStylesheet($this->baseUrl('/public/css/jquery.multiSelect.css'), 'screen,projection')
    ->appendStylesheet($this->baseUrl('/public/css/jquery.uploadify.css'), 'screen,projection')
    ->appendStylesheet($this->baseUrl('/public/css/mybase.modal.css'), 'screen,projection')
    ->appendStylesheet($this->baseUrl('/public/css/mybase.tooltip.css'), 'screen,projection')
    ->appendStylesheet($this->baseUrl('/public/css/layout.css'), 'screen,projection');
    
$this->headScript()
	->appendFile($this->baseUrl('/public/js/jquery.js'))
	->appendFile($this->baseUrl('/public/js/jquery.multiSelect.js'))
	->appendFile($this->baseUrl('/public/js/jquery.uploadify.js'))
	->appendFile($this->baseUrl('/public/js/swfobject.js'))
	->appendFile($this->baseUrl('/public/js/mybase.modal.js'))
	->appendFile($this->baseUrl('/public/js/mybase.tooltip.js'))
	->appendFile($this->baseUrl('/public/js/mybase.js'));    

echo $this->doctype(); ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<?php
	echo $this->headMeta();
	echo $this->headTitle();
	echo $this->headLink();
	echo $this->headScript();
	?>
</head>
<body>	

<div id="header">
	<div class="wrap940">
		<h1>Projekt <span>Company</span></h1>
		<div id="userinfo">
			<?php $session = new Zend_Session_Namespace('Zend_Auth'); ?>
			<?php echo $this->gravatar($session->storage->email); ?>
			<a href="<?php echo $this->baseUrl('people/edit/'.$session->storage->iduser) ; ?>"><?php echo $session->storage->name .' '. $session->storage->surname; ?></a>
			<a href="<?php echo $this->baseUrl('auth/logout') ; ?>" class="logout">Logout</a>
		</div>
	</div>
</div>

<div id="menu">
	<div class="wrap940">
		<?php 
		$acl = Zend_Registry::get('acl');
		$this->navigation()->setAcl($acl)->setRole($session->storage->email);
		echo $this->navigation()->menu()->setMaxDepth(0); ?>
	</div>

	<div id="submenu">
		<div class="wrap940">
			<?php 
				if($this->param('projekt') > 0){
					$options = array(    
						'ulClass'		   => 'subnavigation',    
						'indent'           => 4,    
						'minDepth'         => null,    
						'maxDepth'         => 1,    
						'onlyActiveBranch' => true,    
						'renderParents'    => false
					);
					//echo $this->navigation()->menu()->renderSubMenu(null, 'subnavigation', 4);
					echo $this->navigation()->menu()->renderMenu(null, $options);
				}
			?>
		</div>
	</div>
</div>

<div class="wrap940">	  

	<?php echo $this->layout()->content ?>
	
	<br class="clear" />
</div>	

</body>
</html>